/** Copyright (c) 2023 Mesibo, Inc
 * https://mesibo.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the terms and condition mentioned
 * on https://mesibo.com as well as following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions, the following disclaimer and links to documentation and
 * source code repository.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of Mesibo nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior
 * written permission.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Documentation
 * https://mesibo.com/documentation/
 *
 * Source Code Repository
 * https://github.com/mesibo/ui-modules-ios
 *
 */

#import "TextToEmoji.h"


@implementation TextToEmoji

static NSDictionary *dictemoji ;

+(TextToEmoji *)getInstance {
    static TextToEmoji *myInstance = nil;
    if(nil == myInstance) {
        @synchronized(self) {
            if (nil == myInstance) {
                myInstance = [[self alloc] init];
                if(nil == dictemoji) {
                    dictemoji = [NSDictionary dictionaryWithObjectsAndKeys:
                                 
                                 @(0x1F44D), @":+1:",
                                 @(0x1F44E), @":-1:",
                                 @(0x1F4AF), @":100:",
                                 @(0x1F522), @":1234:",
                                 @(0x1F3B1), @":8ball:",
                                 @(0x1F170), @":a:",
                                 @(0x1F18E), @":ab:",
                                 @(0x1F524), @":abc:",
                                 @(0x1F521), @":abcd:",
                                 @(0x1F251), @":accept:",
                                 @(0x1F6A1), @":aerial_tramway:",
                                 @(0x1F47D), @":alien:",
                                 @(0x1F691), @":ambulance:",
                                 @(0x1F47C), @":angel:",
                                 @(0x1F4A2), @":anger:",
                                 @(0x1F620), @":angry:",
                                 @(0x1F627), @":anguished:",
                                 @(0x1F41C), @":ant:",
                                 @(0x1F34E), @":apple:",
                                 @(0x1F53D), @":arrow_down_small:",
                                 @(0x1F53C), @":arrow_up_small:",
                                 @(0x1F503), @":arrows_clockwise:",
                                 @(0x1F504), @":arrows_counterclockwise:",
                                 @(0x1F3A8), @":art:",
                                 @(0x1F69B), @":articulated_lorry:",
                                 @(0x1F632), @":astonished:",
                                 @(0x1F45F), @":athletic_shoe:",
                                 @(0x1F3E7), @":atm:",
                                 @(0x1F171), @":b:",
                                 @(0x1F476), @":baby:",
                                 @(0x1F37C), @":baby_bottle:",
                                 @(0x1F424), @":baby_chick:",
                                 @(0x1F6BC), @":baby_symbol:",
                                 @(0x1F519), @":back:",
                                 @(0x1F6C4), @":baggage_claim:",
                                 @(0x1F388), @":balloon:",
                                 @(0x1F38D), @":bamboo:",
                                 @(0x1F34C), @":banana:",
                                 @(0x1F3E6), @":bank:",
                                 @(0x1F4CA), @":bar_chart:",
                                 @(0x1F488), @":barber:",
                                 @(0x1F3C0), @":basketball:",
                                 @(0x1F6C0), @":bath:",
                                 @(0x1F6C1), @":bathtub:",
                                 @(0x1F50B), @":battery:",
                                 @(0x1F43B), @":bear:",
                                 @(0x1F41D), @":bee:",
                                 @(0x1F37A), @":beer:",
                                 @(0x1F37B), @":beers:",
                                 @(0x1F41E), @":beetle:",
                                 @(0x1F530), @":beginner:",
                                 @(0x1F514), @":bell:",
                                 @(0x1F371), @":bento:",
                                 @(0x1F6B4), @":bicyclist:",
                                 @(0x1F6B2), @":bike:",
                                 @(0x1F459), @":bikini:",
                                 @(0x1F426), @":bird:",
                                 @(0x1F382), @":birthday:",
                                 @(0x1F0CF), @":black_joker:",
                                 @(0x1F532), @":black_square_button:",
                                 @(0x1F33C), @":blossom:",
                                 @(0x1F421), @":blowfish:",
                                 @(0x1F4D8), @":blue_book:",
                                 @(0x1F699), @":blue_car:",
                                 @(0x1F499), @":blue_heart:",
                                 @(0x1F60A), @":blush:",
                                 @(0x1F417), @":boar:",
                                 @(0x1F4A3), @":bomb:",
                                 @(0x1F4D6), @":book:",
                                 @(0x1F516), @":bookmark:",
                                 @(0x1F4D1), @":bookmark_tabs:",
                                 @(0x1F4DA), @":books:",
                                 @(0x1F4A5), @":boom:",
                                 @(0x1F462), @":boot:",
                                 @(0x1F490), @":bouquet:",
                                 @(0x1F647), @":bow:",
                                 @(0x1F3B3), @":bowling:",
                                 @(0x1F466), @":boy:",
                                 @(0x1F35E), @":bread:",
                                 @(0x1F470), @":bride_with_veil:",
                                 @(0x1F309), @":bridge_at_night:",
                                 @(0x1F4BC), @":briefcase:",
                                 @(0x1F494), @":broken_heart:",
                                 @(0x1F41B), @":bug:",
                                 @(0x1F4A1), @":bulb:",
                                 @(0x1F685), @":bullettrain_front:",
                                 @(0x1F684), @":bullettrain_side:",
                                 @(0x1F68C), @":bus:",
                                 @(0x1F68F), @":busstop:",
                                 @(0x1F464), @":bust_in_silhouette:",
                                 @(0x1F465), @":busts_in_silhouette:",
                                 @(0x1F335), @":cactus:",
                                 @(0x1F370), @":cake:",
                                 @(0x1F4C6), @":calendar:",
                                 @(0x1F4F2), @":calling:",
                                 @(0x1F42B), @":camel:",
                                 @(0x1F4F7), @":camera:",
                                 @(0x1F36C), @":candy:",
                                 @(0x1F520), @":capital_abcd:",
                                 @(0x1F697), @":car:",
                                 @(0x1F4C7), @":card_index:",
                                 @(0x1F3A0), @":carousel_horse:",
                                 @(0x1F431), @":cat:",
                                 @(0x1F408), @":cat2:",
                                 @(0x1F4BF), @":cd:",
                                 @(0x1F4B9), @":chart:",
                                 @(0x1F4C9), @":chart_with_downwards_trend:",
                                 @(0x1F4C8), @":chart_with_upwards_trend:",
                                 @(0x1F3C1), @":checkered_flag:",
                                 @(0x1F352), @":cherries:",
                                 @(0x1F338), @":cherry_blossom:",
                                 @(0x1F330), @":chestnut:",
                                 @(0x1F414), @":chicken:",
                                 @(0x1F6B8), @":children_crossing:",
                                 @(0x1F36B), @":chocolate_bar:",
                                 @(0x1F384), @":christmas_tree:",
                                 @(0x1F3A6), @":cinema:",
                                 @(0x1F3AA), @":circus_tent:",
                                 @(0x1F307), @":city_sunrise:",
                                 @(0x1F306), @":city_sunset:",
                                 @(0x1F191), @":cl:",
                                 @(0x1F44F), @":clap:",
                                 @(0x1F3AC), @":clapper:",
                                 @(0x1F4CB), @":clipboard:",
                                 @(0x1F550), @":clock1:",
                                 @(0x1F559), @":clock10:",
                                 @(0x1F565), @":clock1030:",
                                 @(0x1F55A), @":clock11:",
                                 @(0x1F566), @":clock1130:",
                                 @(0x1F55B), @":clock12:",
                                 @(0x1F567), @":clock1230:",
                                 @(0x1F55C), @":clock130:",
                                 @(0x1F551), @":clock2:",
                                 @(0x1F55D), @":clock230:",
                                 @(0x1F552), @":clock3:",
                                 @(0x1F55E), @":clock330:",
                                 @(0x1F553), @":clock4:",
                                 @(0x1F55F), @":clock430:",
                                 @(0x1F554), @":clock5:",
                                 @(0x1F560), @":clock530:",
                                 @(0x1F555), @":clock6:",
                                 @(0x1F561), @":clock630:",
                                 @(0x1F556), @":clock7:",
                                 @(0x1F562), @":clock730:",
                                 @(0x1F557), @":clock8:",
                                 @(0x1F563), @":clock830:",
                                 @(0x1F558), @":clock9:",
                                 @(0x1F564), @":clock930:",
                                 @(0x1F4D5), @":closed_book:",
                                 @(0x1F510), @":closed_lock_with_key:",
                                 @(0x1F302), @":closed_umbrella:",
                                 @(0x1F378), @":cocktail:",
                                 @(0x1F630), @":cold_sweat:",
                                 @(0x1F4A5), @":collision:",
                                 @(0x1F4BB), @":computer:",
                                 @(0x1F38A), @":confetti_ball:",
                                 @(0x1F616), @":confounded:",
                                 @(0x1F615), @":confused:",
                                 @(0x1F6A7), @":construction:",
                                 @(0x1F477), @":construction_worker:",
                                 @(0x1F3EA), @":convenience_store:",
                                 @(0x1F36A), @":cookie:",
                                 @(0x1F192), @":cool:",
                                 @(0x1F46E), @":cop:",
                                 @(0x1F33D), @":corn:",
                                 @(0x1F46B), @":couple:",
                                 @(0x1F491), @":couple_with_heart:",
                                 @(0x1F48F), @":couplekiss:",
                                 @(0x1F42E), @":cow:",
                                 @(0x1F404), @":cow2:",
                                 @(0x1F4B3), @":credit_card:",
                                 @(0x1F40A), @":crocodile:",
                                 @(0x1F38C), @":crossed_flags:",
                                 @(0x1F451), @":crown:",
                                 @(0x1F622), @":cry:",
                                 @(0x1F63F), @":crying_cat_face:",
                                 @(0x1F52E), @":crystal_ball:",
                                 @(0x1F498), @":cupid:",
                                 @(0x1F4B1), @":currency_exchange:",
                                 @(0x1F35B), @":curry:",
                                 @(0x1F36E), @":custard:",
                                 @(0x1F6C3), @":customs:",
                                 @(0x1F300), @":cyclone:",
                                 @(0x1F483), @":dancer:",
                                 @(0x1F46F), @":dancers:",
                                 @(0x1F361), @":dango:",
                                 @(0x1F3AF), @":dart:",
                                 @(0x1F4A8), @":dash:",
                                 @(0x1F4C5), @":date:",
                                 @(0x1F333), @":deciduous_tree:",
                                 @(0x1F3EC), @":department_store:",
                                 @(0x1F4A0), @":diamond_shape_with_a_dot_inside:",
                                 @(0x1F61E), @":disappointed:",
                                 @(0x1F625), @":disappointed_relieved:",
                                 @(0x1F4AB), @":dizzy:",
                                 @(0x1F635), @":dizzy_face:",
                                 @(0x1F6AF), @":do_not_litter:",
                                 @(0x1F436), @":dog:",
                                 @(0x1F415), @":dog2:",
                                 @(0x1F4B5), @":dollar:",
                                 @(0x1F38E), @":dolls:",
                                 @(0x1F42C), @":dolphin:",
                                 @(0x1F6AA), @":door:",
                                 @(0x1F369), @":doughnut:",
                                 @(0x1F409), @":dragon:",
                                 @(0x1F432), @":dragon_face:",
                                 @(0x1F457), @":dress:",
                                 @(0x1F42A), @":dromedary_camel:",
                                 @(0x1F4A7), @":droplet:",
                                 @(0x1F4C0), @":dvd:",
                                 @(0x1F4E7), @":e-mail:",
                                 @(0x1F442), @":ear:",
                                 @(0x1F33E), @":ear_of_rice:",
                                 @(0x1F30D), @":earth_africa:",
                                 @(0x1F30E), @":earth_americas:",
                                 @(0x1F30F), @":earth_asia:",
                                 @(0x1F373), @":egg:",
                                 @(0x1F346), @":eggplant:",
                                 @(0x1F50C), @":electric_plug:",
                                 @(0x1F418), @":elephant:",
                                 @(0x1F51A), @":end:",
                                 @(0x1F4E9), @":envelope_with_arrow:",
                                 @(0x1F4B6), @":euro:",
                                 @(0x1F3F0), @":european_castle:",
                                 @(0x1F3E4), @":european_post_office:",
                                 @(0x1F332), @":evergreen_tree:",
                                 @(0x1F611), @":expressionless:",
                                 @(0x1F453), @":eyeglasses:",
                                 @(0x1F440), @":eyes:",
                                 @(0x1F44A), @":facepunch:",
                                 @(0x1F3ED), @":factory:",
                                 @(0x1F342), @":fallen_leaf:",
                                 @(0x1F46A), @":family:",
                                 @(0x1F4E0), @":fax:",
                                 @(0x1F628), @":fearful:",
                                 @(0x1F43E), @":feet:",
                                 @(0x1F3A1), @":ferris_wheel:",
                                 @(0x1F4C1), @":file_folder:",
                                 @(0x1F525), @":fire:",
                                 @(0x1F692), @":fire_engine:",
                                 @(0x1F386), @":fireworks:",
                                 @(0x1F313), @":first_quarter_moon:",
                                 @(0x1F31B), @":first_quarter_moon_with_face:",
                                 @(0x1F41F), @":fish:",
                                 @(0x1F365), @":fish_cake:",
                                 @(0x1F3A3), @":fishing_pole_and_fish:",
                                 @(0x1F38F), @":flags:",
                                 @(0x1F526), @":flashlight:",
                                 @(0x1F4BE), @":floppy_disk:",
                                 @(0x1F3B4), @":flower_playing_cards:",
                                 @(0x1F633), @":flushed:",
                                 @(0x1F301), @":foggy:",
                                 @(0x1F3C8), @":football:",
                                 @(0x1F463), @":footprints:",
                                 @(0x1F374), @":fork_and_knife:",
                                 @(0x1F340), @":four_leaf_clover:",
                                 @(0x1F193), @":free:",
                                 @(0x1F364), @":fried_shrimp:",
                                 @(0x1F35F), @":fries:",
                                 @(0x1F438), @":frog:",
                                 @(0x1F626), @":frowning:",
                                 @(0x1F315), @":full_moon:",
                                 @(0x1F31D), @":full_moon_with_face:",
                                 @(0x1F3B2), @":game_die:",
                                 @(0x1F48E), @":gem:",
                                 @(0x1F47B), @":ghost:",
                                 @(0x1F381), @":gift:",
                                 @(0x1F49D), @":gift_heart:",
                                 @(0x1F467), @":girl:",
                                 @(0x1F310), @":globe_with_meridians:",
                                 @(0x1F410), @":goat:",
                                 @(0x1F347), @":grapes:",
                                 @(0x1F34F), @":green_apple:",
                                 @(0x1F4D7), @":green_book:",
                                 @(0x1F49A), @":green_heart:",
                                 @(0x1F62C), @":grimacing:",
                                 @(0x1F601), @":grin:",
                                 @(0x1F600), @":grinning:",
                                 @(0x1F482), @":guardsman:",
                                 @(0x1F3B8), @":guitar:",
                                 @(0x1F52B), @":gun:",
                                 @(0x1F487), @":haircut:",
                                 @(0x1F354), @":hamburger:",
                                 @(0x1F528), @":hammer:",
                                 @(0x1F439), @":hamster:",
                                 @(0x1F45C), @":handbag:",
                                 @(0x1F4A9), @":hankey:",
                                 @(0x1F425), @":hatched_chick:",
                                 @(0x1F423), @":hatching_chick:",
                                 @(0x1F3A7), @":headphones:",
                                 @(0x1F649), @":hear_no_evil:",
                                 @(0x1F49F), @":heart_decoration:",
                                 @(0x1F60D), @":heart_eyes:",
                                 @(0x1F63B), @":heart_eyes_cat:",
                                 @(0x1F493), @":heartbeat:",
                                 @(0x1F497), @":heartpulse:",
                                 @(0x1F4B2), @":heavy_dollar_sign:",
                                 @(0x1F681), @":helicopter:",
                                 @(0x1F33F), @":herb:",
                                 @(0x1F33A), @":hibiscus:",
                                 @(0x1F506), @":high_brightness:",
                                 @(0x1F460), @":high_heel:",
                                 @(0x1F52A), @":hocho:",
                                 @(0x1F36F), @":honey_pot:",
                                 @(0x1F41D), @":honeybee:",
                                 @(0x1F434), @":horse:",
                                 @(0x1F3C7), @":horse_racing:",
                                 @(0x1F3E5), @":hospital:",
                                 @(0x1F3E8), @":hotel:",
                                 @(0x1F3E0), @":house:",
                                 @(0x1F3E1), @":house_with_garden:",
                                 @(0x1F62F), @":hushed:",
                                 @(0x1F368), @":ice_cream:",
                                 @(0x1F366), @":icecream:",
                                 @(0x1F194), @":id:",
                                 @(0x1F250), @":ideograph_advantage:",
                                 @(0x1F47F), @":imp:",
                                 @(0x1F4E5), @":inbox_tray:",
                                 @(0x1F4E8), @":incoming_envelope:",
                                 @(0x1F481), @":information_desk_person:",
                                 @(0x1F607), @":innocent:",
                                 @(0x1F4F1), @":iphone:",
                                 @(0x1F3EE), @":izakaya_lantern:",
                                 @(0x1F383), @":jack_o_lantern:",
                                 @(0x1F5FE), @":japan:",
                                 @(0x1F3EF), @":japanese_castle:",
                                 @(0x1F47A), @":japanese_goblin:",
                                 @(0x1F479), @":japanese_ogre:",
                                 @(0x1F456), @":jeans:",
                                 @(0x1F602), @":joy:",
                                 @(0x1F639), @":joy_cat:",
                                 @(0x1F511), @":key:",
                                 @(0x1F51F), @":keycap_ten:",
                                 @(0x1F458), @":kimono:",
                                 @(0x1F48B), @":kiss:",
                                 @(0x1F617), @":kissing:",
                                 @(0x1F63D), @":kissing_cat:",
                                 @(0x1F61A), @":kissing_closed_eyes:",
                                 @(0x1F618), @":kissing_heart:",
                                 @(0x1F619), @":kissing_smiling_eyes:",
                                 @(0x1F428), @":koala:",
                                 @(0x1F201), @":koko:",
                                 @(0x1F535), @":large_blue_circle:",
                                 @(0x1F537), @":large_blue_diamond:",
                                 @(0x1F536), @":large_orange_diamond:",
                                 @(0x1F317), @":last_quarter_moon:",
                                 @(0x1F31C), @":last_quarter_moon_with_face:",
                                 @(0x1F606), @":laughing:",
                                 @(0x1F343), @":leaves:",
                                 @(0x1F4D2), @":ledger:",
                                 @(0x1F6C5), @":left_luggage:",
                                 @(0x1F34B), @":lemon:",
                                 @(0x1F406), @":leopard:",
                                 @(0x1F688), @":light_rail:",
                                 @(0x1F517), @":link:",
                                 @(0x1F444), @":lips:",
                                 @(0x1F484), @":lipstick:",
                                 @(0x1F512), @":lock:",
                                 @(0x1F50F), @":lock_with_ink_pen:",
                                 @(0x1F36D), @":lollipop:",
                                 @(0x1F4E2), @":loudspeaker:",
                                 @(0x1F3E9), @":love_hotel:",
                                 @(0x1F48C), @":love_letter:",
                                 @(0x1F505), @":low_brightness:",
                                 @(0x1F50D), @":mag:",
                                 @(0x1F50E), @":mag_right:",
                                 @(0x1F004), @":mahjong:",
                                 @(0x1F4EB), @":mailbox:",
                                 @(0x1F4EA), @":mailbox_closed:",
                                 @(0x1F4EC), @":mailbox_with_mail:",
                                 @(0x1F4ED), @":mailbox_with_no_mail:",
                                 @(0x1F468), @":man:",
                                 @(0x1F472), @":man_with_gua_pi_mao:",
                                 @(0x1F473), @":man_with_turban:",
                                 @(0x1F45E), @":mans_shoe:",
                                 @(0x1F341), @":maple_leaf:",
                                 @(0x1F637), @":mask:",
                                 @(0x1F486), @":massage:",
                                 @(0x1F356), @":meat_on_bone:",
                                 @(0x1F4E3), @":mega:",
                                 @(0x1F348), @":melon:",
                                 @(0x1F4DD), @":memo:",
                                 @(0x1F6B9), @":mens:",
                                 @(0x1F687), @":metro:",
                                 @(0x1F3A4), @":microphone:",
                                 @(0x1F52C), @":microscope:",
                                 @(0x1F30C), @":milky_way:",
                                 @(0x1F690), @":minibus:",
                                 @(0x1F4BD), @":minidisc:",
                                 @(0x1F4F4), @":mobile_phone_off:",
                                 @(0x1F4B8), @":money_with_wings:",
                                 @(0x1F4B0), @":moneybag:",
                                 @(0x1F412), @":monkey:",
                                 @(0x1F435), @":monkey_face:",
                                 @(0x1F69D), @":monorail:",
                                 @(0x1F319), @":moon:",
                                 @(0x1F393), @":mortar_board:",
                                 @(0x1F5FB), @":mount_fuji:",
                                 @(0x1F6B5), @":mountain_bicyclist:",
                                 @(0x1F6A0), @":mountain_cableway:",
                                 @(0x1F69E), @":mountain_railway:",
                                 @(0x1F42D), @":mouse:",
                                 @(0x1F401), @":mouse2:",
                                 @(0x1F3A5), @":movie_camera:",
                                 @(0x1F5FF), @":moyai:",
                                 @(0x1F4AA), @":muscle:",
                                 @(0x1F344), @":mushroom:",
                                 @(0x1F3B9), @":musical_keyboard:",
                                 @(0x1F3B5), @":musical_note:",
                                 @(0x1F3BC), @":musical_score:",
                                 @(0x1F507), @":mute:",
                                 @(0x1F485), @":nail_care:",
                                 @(0x1F4DB), @":name_badge:",
                                 @(0x1F454), @":necktie:",
                                 @(0x1F610), @":neutral_face:",
                                 @(0x1F195), @":new:",
                                 @(0x1F311), @":new_moon:",
                                 @(0x1F31A), @":new_moon_with_face:",
                                 @(0x1F4F0), @":newspaper:",
                                 @(0x1F196), @":ng:",
                                 @(0x1F515), @":no_bell:",
                                 @(0x1F6B3), @":no_bicycles:",
                                 @(0x1F6AB), @":no_entry_sign:",
                                 @(0x1F645), @":no_good:",
                                 @(0x1F4F5), @":no_mobile_phones:",
                                 @(0x1F636), @":no_mouth:",
                                 @(0x1F6B7), @":no_pedestrians:",
                                 @(0x1F6AD), @":no_smoking:",
                                 @(0x1F6B1), @":non-potable_water:",
                                 @(0x1F443), @":nose:",
                                 @(0x1F4D3), @":notebook:",
                                 @(0x1F4D4), @":notebook_with_decorative_cover:",
                                 @(0x1F3B6), @":notes:",
                                 @(0x1F529), @":nut_and_bolt:",
                                 @(0x1F17E), @":o2:",
                                 @(0x1F30A), @":ocean:",
                                 @(0x1F419), @":octopus:",
                                 @(0x1F362), @":oden:",
                                 @(0x1F3E2), @":office:",
                                 @(0x1F197), @":ok:",
                                 @(0x1F44C), @":ok_hand:",
                                 @(0x1F646), @":ok_woman:",
                                 @(0x1F474), @":older_man:",
                                 @(0x1F475), @":older_woman:",
                                 @(0x1F51B), @":on:",
                                 @(0x1F698), @":oncoming_automobile:",
                                 @(0x1F68D), @":oncoming_bus:",
                                 @(0x1F694), @":oncoming_police_car:",
                                 @(0x1F696), @":oncoming_taxi:",
                                 @(0x1F4D6), @":open_book:",
                                 @(0x1F4C2), @":open_file_folder:",
                                 @(0x1F450), @":open_hands:",
                                 @(0x1F62E), @":open_mouth:",
                                 @(0x1F4D9), @":orange_book:",
                                 @(0x1F4E4), @":outbox_tray:",
                                 @(0x1F402), @":ox:",
                                 @(0x1F4E6), @":package:",
                                 @(0x1F4C4), @":page_facing_up:",
                                 @(0x1F4C3), @":page_with_curl:",
                                 @(0x1F4DF), @":pager:",
                                 @(0x1F334), @":palm_tree:",
                                 @(0x1F43C), @":panda_face:",
                                 @(0x1F4CE), @":paperclip:",
                                 @(0x1F17F), @":parking:",
                                 @(0x1F6C2), @":passport_control:",
                                 @(0x1F43E), @":paw_prints:",
                                 @(0x1F351), @":peach:",
                                 @(0x1F350), @":pear:",
                                 @(0x1F4DD), @":pencil:",
                                 @(0x1F427), @":penguin:",
                                 @(0x1F614), @":pensive:",
                                 @(0x1F3AD), @":performing_arts:",
                                 @(0x1F623), @":persevere:",
                                 @(0x1F64D), @":person_frowning:",
                                 @(0x1F471), @":person_with_blond_hair:",
                                 @(0x1F64E), @":person_with_pouting_face:",
                                 @(0x1F437), @":pig:",
                                 @(0x1F416), @":pig2:",
                                 @(0x1F43D), @":pig_nose:",
                                 @(0x1F48A), @":pill:",
                                 @(0x1F34D), @":pineapple:",
                                 @(0x1F355), @":pizza:",
                                 @(0x1F447), @":point_down:",
                                 @(0x1F448), @":point_left:",
                                 @(0x1F449), @":point_right:",
                                 @(0x1F446), @":point_up_2:",
                                 @(0x1F693), @":police_car:",
                                 @(0x1F429), @":poodle:",
                                 @(0x1F4A9), @":poop:",
                                 @(0x1F3E3), @":post_office:",
                                 @(0x1F4EF), @":postal_horn:",
                                 @(0x1F4EE), @":postbox:",
                                 @(0x1F6B0), @":potable_water:",
                                 @(0x1F45D), @":pouch:",
                                 @(0x1F357), @":poultry_leg:",
                                 @(0x1F4B7), @":pound:",
                                 @(0x1F63E), @":pouting_cat:",
                                 @(0x1F64F), @":pray:",
                                 @(0x1F478), @":princess:",
                                 @(0x1F44A), @":punch:",
                                 @(0x1F49C), @":purple_heart:",
                                 @(0x1F45B), @":purse:",
                                 @(0x1F4CC), @":pushpin:",
                                 @(0x1F6AE), @":put_litter_in_its_place:",
                                 @(0x1F430), @":rabbit:",
                                 @(0x1F407), @":rabbit2:",
                                 @(0x1F40E), @":racehorse:",
                                 @(0x1F4FB), @":radio:",
                                 @(0x1F518), @":radio_button:",
                                 @(0x1F621), @":rage:",
                                 @(0x1F683), @":railway_car:",
                                 @(0x1F308), @":rainbow:",
                                 @(0x1F64C), @":raised_hands:",
                                 @(0x1F64B), @":raising_hand:",
                                 @(0x1F40F), @":ram:",
                                 @(0x1F35C), @":ramen:",
                                 @(0x1F400), @":rat:",
                                 @(0x1F697), @":red_car:",
                                 @(0x1F534), @":red_circle:",
                                 @(0x1F60C), @":relieved:",
                                 @(0x1F501), @":repeat:",
                                 @(0x1F502), @":repeat_one:",
                                 @(0x1F6BB), @":restroom:",
                                 @(0x1F49E), @":revolving_hearts:",
                                 @(0x1F380), @":ribbon:",
                                 @(0x1F35A), @":rice:",
                                 @(0x1F359), @":rice_ball:",
                                 @(0x1F358), @":rice_cracker:",
                                 @(0x1F391), @":rice_scene:",
                                 @(0x1F48D), @":ring:",
                                 @(0x1F680), @":rocket:",
                                 @(0x1F3A2), @":roller_coaster:",
                                 @(0x1F413), @":rooster:",
                                 @(0x1F339), @":rose:",
                                 @(0x1F6A8), @":rotating_light:",
                                 @(0x1F4CD), @":round_pushpin:",
                                 @(0x1F6A3), @":rowboat:",
                                 @(0x1F3C9), @":rugby_football:",
                                 @(0x1F3C3), @":runner:",
                                 @(0x1F3C3), @":running:",                                                                         
                                 @(0x1F3BD), @":running_shirt_with_sash:",                                                         
                                 @(0x1F202), @":sa:",                                                                              
                                 @(0x1F376), @":sake:",                                                                            
                                 @(0x1F461), @":sandal:",                                                                          
                                 @(0x1F385), @":santa:",                                                                           
                                 @(0x1F4E1), @":satellite:",                                                                       
                                 @(0x1F606), @":satisfied:",                                                                       
                                 @(0x1F3B7), @":saxophone:",                                                                       
                                 @(0x1F3EB), @":school:",                                                                          
                                 @(0x1F392), @":school_satchel:",                                                                  
                                 @(0x1F631), @":scream:",                                                                          
                                 @(0x1F640), @":scream_cat:",                                                                      
                                 @(0x1F4DC), @":scroll:",                                                                          
                                 @(0x1F4BA), @":seat:",                                                                            
                                 @(0x1F648), @":see_no_evil:",                                                                     
                                 @(0x1F331), @":seedling:",                                                                        
                                 @(0x1F367), @":shaved_ice:",                                                                      
                                 @(0x1F411), @":sheep:",                                                                           
                                 @(0x1F41A), @":shell:",                                                                           
                                 @(0x1F6A2), @":ship:",                                                                            
                                 @(0x1F455), @":shirt:",                                                                           
                                 @(0x1F4A9), @":shit:",                                                                            
                                 @(0x1F45E), @":shoe:",                                                                            
                                 @(0x1F6BF), @":shower:",                                                                          
                                 @(0x1F4F6), @":signal_strength:",                                                                 
                                 @(0x1F52F), @":six_pointed_star:",                                                                
                                 @(0x1F3BF), @":ski:",                                                                             
                                 @(0x1F480), @":skull:",                                                                           
                                 @(0x1F634), @":sleeping:",                                                                        
                                 @(0x1F62A), @":sleepy:",                                                                          
                                 @(0x1F3B0), @":slot_machine:",                                                                    
                                 @(0x1F539), @":small_blue_diamond:",                                                              
                                 @(0x1F538), @":small_orange_diamond:",                                                            
                                 @(0x1F53A), @":small_red_triangle:",                                                              
                                 @(0x1F53B), @":small_red_triangle_down:",                                                         
                                 @(0x1F604), @":smile:",                                                                           
                                 @(0x1F638), @":smile_cat:",                                                                       
                                 @(0x1F603), @":smiley:",                                                                          
                                 @(0x1F63A), @":smiley_cat:",                                                                      
                                 @(0x1F608), @":smiling_imp:",                                                                     
                                 @(0x1F60F), @":smirk:",                                                                           
                                 @(0x1F63C), @":smirk_cat:",                                                                       
                                 @(0x1F6AC), @":smoking:",                                                                         
                                 @(0x1F40C), @":snail:",                                                                           
                                 @(0x1F40D), @":snake:",                                                                           
                                 @(0x1F3C2), @":snowboarder:",                                                                     
                                 @(0x1F62D), @":sob:",                                                                             
                                 @(0x1F51C), @":soon:",                                                                            
                                 @(0x1F198), @":sos:",                                                                             
                                 @(0x1F509), @":sound:",                                                                           
                                 @(0x1F47E), @":space_invader:",                                                                   
                                 @(0x1F35D), @":spaghetti:",                                                                       
                                 @(0x1F387), @":sparkler:",                                                                        
                                 @(0x1F496), @":sparkling_heart:",                                                                 
                                 @(0x1F64A), @":speak_no_evil:",                                                                   
                                 @(0x1F50A), @":speaker:",                                                                         
                                 @(0x1F4AC), @":speech_balloon:",                                                                  
                                 @(0x1F6A4), @":speedboat:",                                                                       
                                 @(0x1F31F), @":star2:",                                                                           
                                 @(0x1F303), @":stars:",                                                                           
                                 @(0x1F689), @":station:",                                                                         
                                 @(0x1F5FD), @":statue_of_liberty:",                                                               
                                 @(0x1F682), @":steam_locomotive:",                                                                
                                 @(0x1F372), @":stew:",                                                                            
                                 @(0x1F4CF), @":straight_ruler:",                                                                  
                                 @(0x1F353), @":strawberry:",                                                                      
                                 @(0x1F61B), @":stuck_out_tongue:",                                                                
                                 @(0x1F61D), @":stuck_out_tongue_closed_eyes:",                                                    
                                 @(0x1F61C), @":stuck_out_tongue_winking_eye:",                                                    
                                 @(0x1F31E), @":sun_with_face:",                                                                   
                                 @(0x1F33B), @":sunflower:",                                                                       
                                 @(0x1F60E), @":sunglasses:",                                                                      
                                 @(0x1F305), @":sunrise:",                                                                         
                                 @(0x1F304), @":sunrise_over_mountains:",                                                          
                                 @(0x1F3C4), @":surfer:",                                                                          
                                 @(0x1F363), @":sushi:",                                                                           
                                 @(0x1F69F), @":suspension_railway:",                                                              
                                 @(0x1F613), @":sweat:",                                                                           
                                 @(0x1F4A6), @":sweat_drops:",                                                                     
                                 @(0x1F605), @":sweat_smile:",                                                                     
                                 @(0x1F360), @":sweet_potato:",                                                                    
                                 @(0x1F3CA), @":swimmer:",                                                                         
                                 @(0x1F523), @":symbols:",                                                                         
                                 @(0x1F489), @":syringe:",                                                                         
                                 @(0x1F389), @":tada:",                                                                            
                                 @(0x1F38B), @":tanabata_tree:",                                                                   
                                 @(0x1F34A), @":tangerine:",                                                                       
                                 @(0x1F695), @":taxi:",                                                                            
                                 @(0x1F375), @":tea:",                                                                             
                                 @(0x1F4DE), @":telephone_receiver:",                                                              
                                 @(0x1F52D), @":telescope:",                                                                       
                                 @(0x1F3BE), @":tennis:",                                                                          
                                 @(0x1F4AD), @":thought_balloon:",                                                                 
                                 @(0x1F44E), @":thumbsdown:",                                                                      
                                 @(0x1F44D), @":thumbsup:",                                                                        
                                 @(0x1F3AB), @":ticket:",                                                                          
                                 @(0x1F42F), @":tiger:",                                                                           
                                 @(0x1F405), @":tiger2:",                                                                          
                                 @(0x1F62B), @":tired_face:",                                                                      
                                 @(0x1F6BD), @":toilet:",                                                                          
                                 @(0x1F5FC), @":tokyo_tower:",                                                                     
                                 @(0x1F345), @":tomato:",                                                                          
                                 @(0x1F445), @":tongue:",                                                                          
                                 @(0x1F51D), @":top:",                                                                             
                                 @(0x1F3A9), @":tophat:",                                                                          
                                 @(0x1F69C), @":tractor:",                                                                         
                                 @(0x1F6A5), @":traffic_light:",                                                                   
                                 @(0x1F683), @":train:",                                                                           
                                 @(0x1F686), @":train2:",                                                                          
                                 @(0x1F68A), @":tram:",                                                                            
                                 @(0x1F6A9), @":triangular_flag_on_post:",                                                         
                                 @(0x1F4D0), @":triangular_ruler:",                                                                
                                 @(0x1F531), @":trident:",                                                                         
                                 @(0x1F624), @":triumph:",                                                                         
                                 @(0x1F68E), @":trolleybus:",                                                                      
                                 @(0x1F3C6), @":trophy:",                                                                          
                                 @(0x1F379), @":tropical_drink:",                                                                  
                                 @(0x1F420), @":tropical_fish:",                                                                   
                                 @(0x1F69A), @":truck:",                                                                           
                                 @(0x1F3BA), @":trumpet:",                                                                         
                                 @(0x1F455), @":tshirt:",                                                                          
                                 @(0x1F337), @":tulip:",                                                                           
                                 @(0x1F422), @":turtle:",                                                                          
                                 @(0x1F4FA), @":tv:",                                                                              
                                 @(0x1F500), @":twisted_rightwards_arrows:",                                                       
                                 @(0x1F495), @":two_hearts:",                                                                      
                                 @(0x1F46C), @":two_men_holding_hands:",                                                           
                                 @(0x1F46D), @":two_women_holding_hands:",                                                         
                                 @(0x1F239), @":u5272:",                                                                           
                                 @(0x1F234), @":u5408:",                                                                           
                                 @(0x1F23A), @":u55b6:",                                                                           
                                 @(0x1F22F), @":u6307:",                                                                           
                                 @(0x1F237), @":u6708:",                                                                           
                                 @(0x1F236), @":u6709:",                                                                           
                                 @(0x1F235), @":u6e80:",                                                                           
                                 @(0x1F21A), @":u7121:",                                                                           
                                 @(0x1F238), @":u7533:",                                                                           
                                 @(0x1F232), @":u7981:",                                                                           
                                 @(0x1F233), @":u7a7a:",                                                                           
                                 @(0x1F612), @":unamused:",                                                                        
                                 @(0x1F51E), @":underage:",                                                                        
                                 @(0x1F513), @":unlock:",                                                                          
                                 @(0x1F199), @":up:",                                                                              
                                 @(0x1F6A6), @":vertical_traffic_light:",                                                          
                                 @(0x1F4FC), @":vhs:",                                                                             
                                 @(0x1F4F3), @":vibration_mode:",                                                                  
                                 @(0x1F4F9), @":video_camera:",                                                                    
                                 @(0x1F3AE), @":video_game:",                                                                      
                                 @(0x1F3BB), @":violin:",                                                                          
                                 @(0x1F30B), @":volcano:",                                                                         
                                 @(0x1F19A), @":vs:",                                                                              
                                 @(0x1F6B6), @":walking:",                                                                         
                                 @(0x1F318), @":waning_crescent_moon:",                                                            
                                 @(0x1F316), @":waning_gibbous_moon:",                                                             
                                 @(0x1F403), @":water_buffalo:",                                                                   
                                 @(0x1F349), @":watermelon:",                                                                      
                                 @(0x1F44B), @":wave:",                                                                            
                                 @(0x1F312), @":waxing_crescent_moon:",
                                 @(0x1F314), @":waxing_gibbous_moon:",                                                             
                                 @(0x1F6BE), @":wc:",
                                 @(0x1F629), @":weary:",
                                 @(0x1F492), @":wedding:",
                                 @(0x1F433), @":whale:" ,
                                 @(0x1F40B), @":whale2:",
                                 @(0x1F4AE), @":white_flower:",
                                 @(0x1F533), @":white_square_button:" ,
                                 @(0x1F390), @":wind_chime:" ,
                                 @(0x1F377), @":wine_glass:" ,
                                 @(0x1F609), @":wink:" ,
                                 @(0x1F43A), @":wolf:" ,
                                 @(0x1F469), @":woman:",
                                 @(0x1F45A), @":womans_clothes:" ,
                                 @(0x1F452), @":womans_hat:" ,
                                 @(0x1F6BA), @":womens:" ,
                                 @(0x1F61F), @":worried:",
                                 @(0x1F527), @":wrench:",
                                 @(0x1F49B), @":yellow_heart:" ,
                                 @(0x1F4B4), @":yen:",
                                 @(0x1F60B), @":yum:",
                                 @(0x1F4A4), @":zzz:",

                                 
                                 nil];
                }
            }
            
        }
    }
    
    
    return myInstance;
}




- (NSArray*) getEmojiTextStrings {
    return dictemoji.allKeys;
}


- (NSString *) getEmojiValueForString : (NSString *) key{
    uint32_t returnValue = (uint32_t)[[dictemoji valueForKey:key] unsignedIntValue];
    NSString *retrnString = [[NSString alloc] initWithBytes:&returnValue length:sizeof(returnValue) encoding:NSUTF32LittleEndianStringEncoding];
    return retrnString;
}


@end
